export const businessData = [
    {
      imageSrc: "https://content.codecademy.com/programs/react/ravenous/pizza.jpg",
      name: "MarginOtto Pizzeria",
      address: "1010 Paddington Way",
      city: "Flavortown",
      state: "NY",
      zipCode: "10101",
      category: "Italian",
      rating: 4.5,
      reviewCount: 90,
    },
    {
      imageSrc: "https://content.codecademy.com/programs/react/ravenous/pizza.jpg",
      name: "Burger Builder",
      address: "2020 Ranch Road",
      city: "Meatville",
      state: "TX",
      zipCode: "20202",
      category: "American",
      rating: 4.2,
      reviewCount: 120,
    },
    {
      imageSrc: "https://content.codecademy.com/programs/react/ravenous/pizza.jpg",
      name: "Taco Tower",
      address: "3030 Corn Avenue",
      city: "Tastytown",
      state: "CA",
      zipCode: "30303",
      category: "Mexican",
      rating: 4.8,
      reviewCount: 85,
    },
    {
      imageSrc: "https://content.codecademy.com/programs/react/ravenous/pizza.jpg",
      name: "Sushi Sunset",
      address: "4040 Rice Boulevard",
      city: "Freshfish",
      state: "WA",
      zipCode: "40404",
      category: "Japanese",
      rating: 4.7,
      reviewCount: 74,
    },
    {
      imageSrc: "https://content.codecademy.com/programs/react/ravenous/pizza.jpg",
      name: "Dim Sum Delight",
      address: "5050 Dumpling Drive",
      city: "Chinatown",
      state: "NY",
      zipCode: "50505",
      category: "Chinese",
      rating: 4.4,
      reviewCount: 67,
    },
    {
      imageSrc: "https://content.codecademy.com/programs/react/ravenous/pizza.jpg",
      name: "Pho Real",
      address: "6060 Noodle Way",
      city: "Soup City",
      state: "CA",
      zipCode: "60606",
      category: "Vietnamese",
      rating: 4.6,
      reviewCount: 95,
    },
    {
      imageSrc: "https://content.codecademy.com/programs/react/ravenous/pizza.jpg",
      name: "Curry Up Now",
      address: "7070 Spice Blvd",
      city: "Flavor Town",
      state: "NJ",
      zipCode: "70707",
      category: "Indian",
      rating: 4.3,
      reviewCount: 100,
    },
    {
      imageSrc: "https://content.codecademy.com/programs/react/ravenous/pizza.jpg",
      name: "Steak Station",
      address: "8080 Beef Bend",
      city: "Grillville",
      state: "TX",
      zipCode: "80808",
      category: "Steakhouse",
      rating: 4.9,
      reviewCount: 130,
    },
    {
      imageSrc: "https://content.codecademy.com/programs/react/ravenous/pizza.jpg",
      name: "Garden Fresh",
      address: "9090 Veggie Patch",
      city: "Greensville",
      state: "OR",
      zipCode: "90909",
      category: "Vegan",
      rating: 4.1,
      reviewCount: 45,
    }
  ];
  